name: Deploy to cPanel

on:
  push:
    branches:
      - main

concurrency:
  group: cpanel-deploy
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install Dependencies
        run: npm ci

      - name: Build Project
        run: npm run build

      - name: Setup SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.CPANEL_SSH_KEY_B64 }}" | base64 -d > ~/.ssh/deploy_key
          chmod 600 ~/.ssh/deploy_key

      - name: Test SSH Connection
        run: |
          ssh -p 5726 \
          -i ~/.ssh/deploy_key \
          -o StrictHostKeyChecking=no \
          waqtmoney@103.234.185.16 "echo Connected Successfully"

      - name: Deploy to cPanel
        run: |
          rsync -avz --delete \
          -e "ssh -p 5726 -i ~/.ssh/deploy_key -o StrictHostKeyChecking=no" \
          dist/ \
          waqtmoney@103.234.185.16:/home/waqtmoney/public_html/waqt-testing/